# Generated by Django 5.2.3 on 2025-06-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
